baseurl = "https://hugo.shashankpatel.com/"
languageCode = "en-us"
languageLang = "en"
title = "Homepage"
theme = "hugo-webslides"

disableKinds = ["sitemap", "RSS"]
tags = ["slide", "presentation", "responsive", "landing page"]
features = ["webslides.js", "pre-made template", "shortcodes"]

[params]
  author = "RCJacH"
  homepage = "RCJacH.github.io"


[params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[blackfriday]
extensionsmask = ["autoHeaderIds"]